# deploy-changes-update-db.yaml
# Description:
#   This flow runs several Liquibase commands to generate information that could be useful for review, auditing
#   and troubleshooting purposes.  It will run in all shared pipeline environments from CI onward.

stages:
  validateChangelog:
    # Run validate on Repo Changelog
    # https://docs.liquibase.com/commands/update/validate.html
    actions:
      - type: liquibase
        command: validate
        cmdArgs: {}

      # Show database status
      # https://docs.liquibase.com/commands/change-tracking/status.html
      - type: liquibase
        command: status
        cmdArgs: { changelog-file: "${LIQUIBASE_COMMAND_CHANGELOG_FILE}", verbose: "true" }

      # Run Checks on Repo Changelog
      # https://docs.liquibase.com/commands/quality-checks/subcommands/run.html
      - type: liquibase
        command: checks run
        cmdArgs:
          { changelog-file: "${LIQUIBASE_COMMAND_CHANGELOG_FILE}",
            checks-scope: "changelog",
            checks-settings-file: "s3://${AWS_S3_BUCKET}/static/checks/liquibase.checks-settings.conf"
          }

  driftDetection:
    # Check if manual updates were made to the environment since last deployment
    actions:
      - type: liquibase
        command: diff
        cmdArgs: 
          { referenceURL: "${LIQUIBASE_COMMAND_REFERENCE_URL}", 
            format: json
          }
  
  tagDatabaseBegin:
    # Tag database current state
    # See https://docs.liquibase.com/commands/change-tracking/tag.html
    actions:
      - type: liquibase
        command: tag
        cmdArgs: 
          { tag: "${LB_DEPLOYMENT}-begin",
            add-row: "true"
          }

  liquibaseUpdate:
    # Run Update on Latest Repo State
    # https://docs.liquibase.com/commands/update/update-sql.html
    actions:
      - type: liquibase
        command: update-sql
        cmdArgs: { }

    # Run Update on Latest Repo State
    # https://docs.liquibase.com/commands/update/update.html
      - type: liquibase
        command: update
        cmdArgs: { }
        
  tagDatabaseEnd:
    # Tag database current state
    # See https://docs.liquibase.com/commands/change-tracking/tag.html
    actions:
      - type: liquibase
        command: tag
        cmdArgs: 
          { tag: "${LB_DEPLOYMENT}-end",
            add-row: "true"
          }
    
  newSnapshot:
    # Upload a new snapshot
    actions:
      - type: liquibase
        command: snapshot
        cmdArgs: 
          { referenceURL: "${LIQUIBASE_COMMAND_REFERENCE_URL}", 
            format: json
          }

endStage:
    actions:
      # Run Checks on Database
      # https://docs.liquibase.com/commands/quality-checks/subcommands/run.html
      - type: liquibase
        command: checks run
        cmdArgs: { checks-scope: "database" }

      # Show history
      # https://docs.liquibase.com/commands/change-tracking/history.html
      - type: liquibase
        command: history
        cmdArgs: {}