# rollback-changes-update-db.yaml
# Description:
#   This flow runs several Liquibase commands to generate information that could be useful for review, auditing
#   and troubleshooting purposes.  It will run in all shared pipeline environments from CI onward.

stages:
  validateChangelog:
    # Run validate on Repo Changelog
    # https://docs.liquibase.com/commands/update/validate.html
    actions:
      - type: liquibase
        command: validate
        cmdArgs: {}

  liquibaseRollbackSQL:
    # Run Rollback-SQL on Latest Repo State
    # https://docs.liquibase.com/commands/rollback/rollback-sql.html
    actions:
      - type: liquibase
        command: rollback-sql
        cmdArgs: { }

  liquibaseRollback:
    actions:
      - type: liquibase
        command: rollback
        cmdArgs: { }
    
  newSnapshot:
    # Upload a new snapshot
    actions:
      - type: liquibase
        command: snapshot
        cmdArgs: 
          { referenceURL: "${LIQUIBASE_COMMAND_REFERENCE_URL}", 
            snapshot-format: json 
          }
        globalArgs: { outputfile: "${LB_SNAPSHOT_OUTPUT_FILE}" }

endStage:
    actions:
      # Show history
      # https://docs.liquibase.com/commands/change-tracking/history.html
      - type: liquibase
        command: history