liquibase.command.url=jdbc:postgresql://dmc-db.liquibase.net:5432/demo_db_dev
#liquibase.command.username: 
#liquibase.command.password: 

#-------------------------------------------------------------------------------
# Differences between environments
#-------------------------------------------------------------------------------
liquibase.command.referenceUrl=jdbc:postgresql://dmc-db.liquibase.net:5432/demo_db_prod
#liquibase.command.referenceUsername: 
#liquibase.command.referencePassword: 

#-------------------------------------------------------------------------------
# Differences between previously saved snapshot
#-------------------------------------------------------------------------------
#liquibase.command.referenceUrl=offline:postgres?snapshot=drift-history/expectedState.json

liquibase.liquibaseSchemaName=abc
liquibase.defaultSchemaName=abc

#-------------------------------------------------------------------------------
# Properties for structured logging
#-------------------------------------------------------------------------------
liquibase.logFormat=JSON_PRETTY
liquibase.logFile=logs/log.json
logLevel: INFO
liquibase.showBanner: false

#-------------------------------------------------------------------------------
# Properties for Drift Reports
#-------------------------------------------------------------------------------
liquibase.reports.enabled=true
liquibase.reports.path=Reports