# .github/workflows/install-postgres-client-tools/action.yml
name: 'Install Postgres Client Tools'
description: 'Sets up pg_dump, pg_restore, and psql'

runs:
  using: 'composite'
  steps:
    - name: Install Postgres Client Tools
      run: |
        echo "Installing PostgreSQL 15 client tools..."
        sudo dnf install -y https://download.postgresql.org/pub/repos/yum/reporpms/EL-9-x86_64/pgdg-redhat-repo-latest.noarch.rpm
        sudo dnf install -y postgresql15 postgresql15-libs
        echo "/usr/bin/pg_dump" >> $GITHUB_PATH
        echo "/usr/bin/pg_restore" >> $GITHUB_PATH
        echo "/usr/bin/psql" >> $GITHUB_PATH

    - name: Check PG client tools installation
      run: |
        echo "pg_dump: $(pg_dump --version || echo 'Not found')"
        echo "pg_restore: $(pg_restore --version || echo 'Not found')"
        echo "psql: $(psql --version || echo 'Not found')"