#############################################################################
#  GitHub Action to perform a build on the first database, eg. DEV,
#  using Liquibase Secure, Flows, Policy checks, and S3.
##############################################################################
name: 'Liquibase Build Job'
run-name: ${{ inputs.environment}} build of current repo by ${{ github.actor }}

on:
  workflow_dispatch:
    # Following are the inputs received via the GitHubActions Run workflow dialog
    inputs:
    
      # The type 'environment' will automatically pull in the environments created in GitHub
      environment:
        description: 'Environment for build'
        type: environment
        required: true
        default: DEV
        
      lb_tag:
        description: 'Optional tag for the build'
        type: string
        required: false


####################################################################
### Include permissions for OIDC
#####################################################################
permissions:
  id-token: write
  contents: write

####################################################################
#  Set up the environment
#####################################################################
env:
  # AWS S3 bucket is the host part of the S3 bucket
  AWS_S3_BUCKET: ${{ vars.AWS_S3_BUCKET }}
  AWS_REGION: ${{ vars.AWS_REGION }}
  
  # AWS Access credentials use by the Liquibase Secure S3 Extension
  # AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  # AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  # AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
  
  # Secure License key
  # See https://docs.liquibase.com/workflows/liquibase-pro/how-to-apply-your-liquibase-pro-license-key.html
  LIQUIBASE_LICENSE_KEY: ${{ secrets.LIQUIBASE_LICENSE_KEY }}
  
  # JDBC URL of the database per environment
  # See https://docs.liquibase.com/workflows/liquibase-community/using-jdbc-url-in-liquibase.html
  LIQUIBASE_COMMAND_URL: ${{ secrets.LIQUIBASE_URL }}

  # Credentials for the environment's database https://docs.liquibase.com/parameters/command-parameters.html
  LIQUIBASE_COMMAND_USERNAME: ${{ secrets.LIQUIBASE_USERNAME }}
  LIQUIBASE_COMMAND_PASSWORD: ${{ secrets.LIQUIBASE_PASSWORD }}

  # Liquibase schema: Specified to allow flexibility in storage of Liquibase Change Tracking Tables
  # See https://docs.liquibase.com/parameters/liquibase-schema-name.html
  LIQUIBASE_LIQUIBASE_SCHEMA_NAME: gha
  
  # Default schema: Specify schema for all changes
  LIQUIBASE_COMMAND_DEFAULT_SCHEMA_NAME: gha
  LIQUIBASE_COMMAND_REFERENCE_DEFAULT_SCHEMA_NAME: gha

  # Search path (See https://docs.liquibase.com/concepts/changelogs/how-liquibase-finds-files.html)
  LIQUIBASE_SEARCH_PATH: flows, checks, changelogs
  
  # The database changelog. See https://docs.liquibase.com/concepts/changelogs/working-with-changelogs.html
  LIQUIBASE_COMMAND_CHANGELOG_FILE: changelog.yaml
  
  ENVIRONMENT: ${{ inputs.environment }}
  BRANCH: ${{ github.ref_name }}
  LB_TAG: ${{ github.event.inputs.lb_tag || github.ref_name }}

  #LIQUIBASE_REPORT_PATH: s3://${{ secrets.AWS_S3_BUCKET }}/gha_reports
  LIQUIBASE_REPORT_PATH: reports
  LIQUIBASE_DBCLHISTORY_ENABLED: true
  
  # Values: OFF, SEVERE, WARNING, INFO, FINE
  LIQUIBASE_LOG_LEVEL: INFO
  LIQUIBASE_LOG_FORMAT: JSON_PRETTY
  LIQUIBASE_LOG_FILE: logs/log.json
  
  # PSQL values
  LIQUIBASE_PSQL_KEEP_TEMP_PATH: reports
  LIQUIBASE_PSQL_LOG_FILE: output.log
  
  # Checks values
  LIQUIBASE_COMMAND_CHECKS_RUN_AUTO_UPDATE: off

jobs:
  #########################################################################
  #  Build
  #########################################################################

  database-build:
    runs-on: [self-hosted]
    environment: ${{ inputs.environment }}
    steps:
    - uses: actions/checkout@v4

###
### Retrieve AWS credentials
### Requires an AWS IAM role with token.actions.githubusercontent.com web identity provider
### Provider URL: https://token.actions.githubusercontent.com
### Audience: sts.amazonaws.com
### Need to grab the license key to install paid version
###
    - name: Retrieving AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE }}
        aws-region: ${{ vars.AWS_REGION }}

    - name: Setup Liquibase Environment
      uses: ./.github/workflows/setup-liquibase

    - name: Liquibase Checks Flow
      id: lbp-policy-checks
      continue-on-error: true
      run: | 
        set +e
        # CHECKS_STATUS=$(liquibase flow --classpath=liquibase-aws-extension.jar --flow-file=liquibase-checks.flowfile.yaml 2>&1)
        CHECKS_STATUS=$(liquibase flow --flow-file=liquibase-checks.flowfile.yaml 2>&1)
        EXIT_CODE=$?
        set -e
        if [ $EXIT_CODE -eq 1 ]; then
          echo "::error::Policy checks did not pass, but allowing build to complete."
          echo "::error::In non-build environments, this deployment will require Manual Approval."
          exit $EXIT_CODE
        fi  

    - name: Configure Git for Actions
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

    - name: Liquibase Build Flow
      run: liquibase flow --flow-file=liquibase-build.flowfile.yaml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Auto-generated

    - name: Upload Reports Artifact
      if: always()
      uses: ./.github/workflows/upload-reports
      with:
        job-type: deploy
        upload-s3: true
