####################################################################
#  GitHub Action to perform an environment-targeted deployment of
#  database changes using Liquibase Pro, Liquibase Pro Flows,
#  Custom Quality checks and S3.
#####################################################################
name: 'Liquibase Pro Deployment Job'
run-name: ${{ inputs.environment}} deployment of current repo by ${{ github.actor }}

on:

  workflow_dispatch:
    # Following are the inputs received via the GitHubActions Run workflow dialog
    inputs:
      # The type 'environment' will automatically pull in the environments created in GitHub
      environment:
        description: 'Environment to deploy to'
        type: environment
        required: true
      # For more info on log level, see: https://docs.liquibase.com/parameters/log-level.html
      log-level:
        description: 'Liquibase log level'
        required: false
        default: 'INFO'
        type: choice
        options: [ 'SEVERE','WARNING','INFO','FINE','OFF' ]

####################################################################
#  Set up the environment
#####################################################################
env:
  # AWS S3 bucket is the host part of the S3 bucket
  AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
  
  # AWS Access credentials use by the Liquibase Pro S3 Extension
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  # Default AWS region
  AWS_REGION: us-east-1
  
  # Pro License key
  # See https://docs.liquibase.com/workflows/liquibase-pro/how-to-apply-your-liquibase-pro-license-key.html
  LIQUIBASE_LICENSE_KEY: ${{ secrets.LIQUIBASE_PRO_LICENSE_KEY }}
  
  # JDBC URL of the database per environment
  # See https://docs.liquibase.com/workflows/liquibase-community/using-jdbc-url-in-liquibase.html
  LIQUIBASE_COMMAND_URL: ${{ secrets.LIQUIBASE_URL }}

  # Credentials for the environment's database https://docs.liquibase.com/parameters/command-parameters.html
  LIQUIBASE_COMMAND_USERNAME: ${{ secrets.LIQUIBASE_USERNAME }}
  LIQUIBASE_COMMAND_PASSWORD: ${{ secrets.LIQUIBASE_PASSWORD }}
  
  # Liquibase schema: Specified to allow flexibility in storage of Liquibase Change Tracking Tables
  # See https://docs.liquibase.com/parameters/liquibase-schema-name.html
  LIQUIBASE_LIQUIBASE_SCHEMA_NAME: abc
  
  # Default schema: Specify schema for all changes
  LIQUIBASE_COMMAND_DEFAULT_SCHEMA_NAME: abc

  # Search path (See https://docs.liquibase.com/concepts/changelogs/how-liquibase-finds-files.html)
  LIQUIBASE_SEARCH_PATH: src/main/resources/changelogs,s3://${{ secrets.AWS_S3_BUCKET }}/static/flows/,s3://${{ secrets.AWS_S3_BUCKET }}/snapshots

  # The database changelog. See https://docs.liquibase.com/concepts/changelogs/working-with-changelogs.html
  LIQUIBASE_COMMAND_CHANGELOG_FILE: "root.yaml"

  # Location of the Quality Checks settings file
  LIQUIBASE_COMMAND_CHECKS_SETTINGS_FILE: s3://${{ secrets.AWS_S3_BUCKET }}/static/checks/liquibase.checks-settings.conf

  # The top level Flow File that orchestrates the database changes. Use 'LB' instead of 'LIQUIBASE' to avoid warning.
  LB_FLOW_FILE: s3://${{ secrets.AWS_S3_BUCKET }}/static/flows/deploy-changes-update-db.yaml

  # Flow environment variables. Use 'LB' instead of 'LIQUIBASE' to avoid warning.
  LB_FLOW_ENV: ${{ inputs.environment }}
  LB_DEPLOYMENT: ${{ github.run_id }}.${{ github.run_number }}
  
  # Drift Settings
  # See https://docs.liquibase.com/tools-integrations/observability/operation-reports-drift-report.html
  LIQUIBASE_COMMAND_REFERENCE_URL: "offline:postgres?snapshot=${{ inputs.environment }}-snapshot.json"
  
  # Logging settings
  LIQUIBASE_REPORTS_ENABLED: true
  LIQUIBASE_REPORTS_PATH: reports
  LIQUIBASE_COMMAND_DIFF_REPORT_NAME: drift_report.html
  LIQUIBASE_COMMAND_DIFF_DRIFT_SEVERITY: 1
  LIQUIBASE_SHOW_BANNER: false
  LIQUIBASE_LOG_FORMAT: JSON_PRETTY
  LIQUIBASE_LOG_FILE: logs/log.json
  LIQUIBASE_LOG_LEVEL: ${{ inputs.log-level || 'SEVERE' }}

jobs:
  #########################################################################
  #  Update using repo
  #########################################################################

  database-deploy:
    runs-on: [self-hosted]
    environment: ${{ inputs.environment }}

    steps:
      # Clean the workspace to help clean up self-Hosted runners prior to deployment
      - uses: AutoModality/action-clean@v1

        # Check out the source code
      - name: Checkout repo
        uses: actions/checkout@v3
        
        # Execute the Flow file
      - name: Run flow
        run: |
          liquibase flow \
             --flow-file=${{ env.LB_FLOW_FILE }}  
       
####################################################################
#  Artifact creation for Reports
####################################################################
  create-reports-artifact:
    needs: [database-deploy]
    runs-on: [self-hosted]
    environment: ${{ inputs.environment }}
    if: always()

    steps:
      # Save reports as artifact
      - uses: actions/upload-artifact@v3
        with:
          name: REPORTS-${{ github.run_id }}.${{ github.run_number }}.zip
          path: reports/