####################################################################
#  GitHub Action to perform an environment-targeted deployment of
#  database changes using Liquibase Pro, Liquibase Pro Flows,
#  Custom Quality checks and S3.
#####################################################################
name: 'Liquibase Pro Deployment Job'
run-name: ${{ inputs.environment}} deployment of ${{ inputs.artifact-version }} by ${{ github.actor }}

on:

  workflow_dispatch:
    # Following are the inputs received via the GitHubActions Run workflow dialog
    inputs:
      # The type 'environment' will automatically pull in the environments created in GitHub
      environment:
        description: 'Environment to deploy to'
        type: environment
        required: true
      # This is a text input for the version of the artifact to pull from Artifactory
      # and use for the deployment. The form is MMMMMMMMM.mm
      artifact-version:
        description: 'Artifact version to deploy:'
        required: true
        type: string
      # For more info on log level, see: https://docs.liquibase.com/parameters/log-level.html
      log-level:
        description: 'Liquibase log level'
        required: false
        default: 'INFO'
        type: choice
        options: [ 'SEVERE','WARNING','INFO','FINE','OFF' ]

####################################################################
#  Set up the environment
#####################################################################
env:
  # Search path (See https://docs.liquibase.com/concepts/changelogs/how-liquibase-finds-files.html)
  LIQUIBASE_SEARCH_PATH: '.'

  # JDBC URL of the database per environment
  # See https://docs.liquibase.com/workflows/liquibase-community/using-jdbc-url-in-liquibase.html
  LIQUIBASE_COMMAND_URL: ${{ secrets.LIQUIBASE_URL }}

  # Credentials for the environment's database https://docs.liquibase.com/parameters/command-parameters.html
  LIQUIBASE_COMMAND_USERNAME: ${{ secrets.LIQUIBASE_USERNAME }}
  LIQUIBASE_COMMAND_PASSWORD: ${{ secrets.LIQUIBASE_PASSWORD }}

  # Pro License key
  # See https://docs.liquibase.com/workflows/liquibase-pro/how-to-apply-your-liquibase-pro-license-key.html
  LIQUIBASE_LICENSE_KEY: ${{ secrets.LIQUIBASE_PRO_LICENSE_KEY }}

  # Token for accessing JFrog Artifactory to upload/download artifacts
  # See https://www.jfrog.com/confluence/display/JFROG/Access+Tokens
  ARTIFACTORY_BEARER_TOKEN: ${{ secrets.ARTIFACTORY_BEARER_TOKEN }}

  # URI Prefix to JFrog Artifactory where artifacts are uploaded/downloaded
  ARTIFACTORY_URI_PREFIX: ${{ secrets.ARTIFACTORY_URI_PREFIX }}

jobs:
  ####################################################################
  #  Artifact download
  ####################################################################
  download-artifact:
    runs-on: [self-hosted]
    environment: ${{ inputs.environment}}

    steps:
      # Clean the workspace to help clean up self-Hosted runners prior to deployment
      - uses: AutoModality/action-clean@v1

      # Download the artifact from JFrog
      # - name: Download artifact into a new directory named artifact
        # run: |
          # mkdir ./artifact
          # curl -H "Authorization: Bearer ${{ env.ARTIFACTORY_BEARER_TOKEN }}" \
            # ${{ env.ARTIFACTORY_URI_PREFIX }}SNAPSHOT-artifact-${{ inputs.artifact-version }}.zip \
             # -O -J -L       
             
      # Download the artifact from GitHub Artifacts
      # - name: Download artifact into a new directory named artifact
        # run: |
          # mkdir ./artifact
          
          # curl -L \
           # -H "Accept: application/vnd.github+json" \
           # -H "Authorization: Bearer <YOUR-TOKEN>" \
           # -H "X-GitHub-Api-Version: 2022-11-28" \
          # https://api.github.com/repos/OWNER/REPO/actions/artifacts/ARTIFACT_ID/ARCHIVE_FORMAT
          
          # curl -H "Authorization: Bearer ${{ env.ARTIFACTORY_BEARER_TOKEN }}" \
            # ${{ env.ARTIFACTORY_URI_PREFIX }}SNAPSHOT-artifact-${{ inputs.artifact-version }}.zip \
             # -O -J -L
             
      - uses: actions/download-artifact@v4
          with:
          name: SNAPSHOT-artifact-7629865294.7.zip
          github-token: ${{ secrets.GH_PAT }} # token with actions:read permissions on target repo
          repository: actions/toolkit
          run-id: 7629865294   

      # Unzip the artifact into the newly created ./artifact directory
      - name: Unzip artifact
        run: |
          unzip SNAPSHOT-artifact-${{ inputs.artifact-version }}.zip -d ./artifact
          du -ah

  ####################################################################
  #  Deploy the artifact to the requested environment
  ####################################################################
  database-deploy:
    needs: [download-artifact]
    runs-on: [self-hosted]
    environment: ${{ inputs.environment}}

    # Execute the DB update from the downloaded and unzipped artifact
    # Note that this artifact is being loaded from ./artifact. Loading different changelogs can
    # cause problems when creating the unique identifier of changesets. In our changelog,
    # we've specified a logicalFilePath which is used as a key to the correct file, regardless of
    # where it resides on the file system
    steps:
      - name: Run liquibase update command
        run: |
          liquibase \
             --log-level=${{ inputs.log-level || 'SEVERE' }} \
             --changelog-file=./artifact/src/main/resources/changelogs/aircraft_changelog.xml \
             update 

