####################################################################
#  GitHub Action to perform an environment-targeted deployment of
#  database changes using Liquibase Pro, Liquibase Pro Flows,
#  Custom Quality checks and S3.
#####################################################################
name: 'Liquibase Pro Deployment Job with Artifact'
run-name: ${{ inputs.environment}} deployment of ${{ inputs.artifact-id }} by ${{ github.actor }}

on:

  workflow_dispatch:
    # Following are the inputs received via the GitHubActions Run workflow dialog
    inputs:
      # The type 'environment' will automatically pull in the environments created in GitHub
      environment:
        description: 'Environment to deploy to'
        type: environment
        required: true
      # This is a text input for the artifact id to pull from GitHub artifacts
      # Copy and paste the URL to the artifact. Artifact ID will be parsed from URL. 
      # Or specify the artifact id.
      artifact-id:
        description: 'Artifact id to deploy:'
        required: true
        type: string
      # For more info on log level, see: https://docs.liquibase.com/parameters/log-level.html
      log-level:
        description: 'Liquibase log level'
        required: false
        default: 'INFO'
        type: choice
        options: [ 'SEVERE','WARNING','INFO','FINE','OFF' ]

####################################################################
#  Set up the environment
#####################################################################
env:
    # AWS S3 bucket is the host part of the S3 bucket
  AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
  
  # AWS Access credentials use by the Liquibase Pro S3 Extension
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  # Default AWS region
  AWS_REGION: us-east-1
  
  # Pro License key
  # See https://docs.liquibase.com/workflows/liquibase-pro/how-to-apply-your-liquibase-pro-license-key.html
  LIQUIBASE_LICENSE_KEY: ${{ secrets.LIQUIBASE_PRO_LICENSE_KEY }}
  
  # JDBC URL of the database per environment
  # See https://docs.liquibase.com/workflows/liquibase-community/using-jdbc-url-in-liquibase.html
  LIQUIBASE_COMMAND_URL: ${{ secrets.LIQUIBASE_URL }}

  # Credentials for the environment's database https://docs.liquibase.com/parameters/command-parameters.html
  LIQUIBASE_COMMAND_USERNAME: ${{ secrets.LIQUIBASE_USERNAME }}
  LIQUIBASE_COMMAND_PASSWORD: ${{ secrets.LIQUIBASE_PASSWORD }}
  
  # Liquibase schema: Specified to allow flexibility in storage of Liquibase Change Tracking Tables
  # See https://docs.liquibase.com/parameters/liquibase-schema-name.html
  LIQUIBASE_LIQUIBASE_SCHEMA_NAME: abc
  
  # Default schema: Specify schema for all changes
  LIQUIBASE_COMMAND_DEFAULT_SCHEMA_NAME: abc

  # Search path (See https://docs.liquibase.com/concepts/changelogs/how-liquibase-finds-files.html)
  LIQUIBASE_SEARCH_PATH: src/main/resources/changelogs,s3://${{ secrets.AWS_S3_BUCKET }}/static/flows/
  #LIQUIBASE_SEARCH_PATH: '.'

  # The database changelog. See https://docs.liquibase.com/concepts/changelogs/working-with-changelogs.html
  LIQUIBASE_COMMAND_CHANGELOG_FILE: "./artifact/src/main/resources/changelogs/root.yaml"

  # Location of the Quality Checks settings file
  LIQUIBASE_COMMAND_CHECKS_SETTINGS_FILE: s3://${{ secrets.AWS_S3_BUCKET }}/static/checks/liquibase.checks-settings.conf

  # The top level Flow File that orchestrates the database changes. Use 'LB' instead of 'LIQUIBASE' to avoid warning.
  LB_FLOW_FILE: s3://${{ secrets.AWS_S3_BUCKET }}/static/flows/deploy-changes-update-db.yaml

  # Flow environment variables. Use 'LB' instead of 'LIQUIBASE' to avoid warning.
  LB_FLOW_ENV: ${{ inputs.environment }}
  LB_DEPLOYMENT: ${{ github.run_id }}.${{ github.run_number }}
  
  # Logging settings
  LIQUIBASE_REPORTS_ENABLED: true
  LIQUIBASE_REPORTS_PATH: reports
  LIQUIBASE_SHOW_BANNER: false
  LIQUIBASE_LOG_FORMAT: JSON_PRETTY
  LIQUIBASE_LOG_FILE: logs/log.json
  LIQUIBASE_LOG_LEVEL: ${{ inputs.log-level || 'SEVERE' }}

jobs:
  ####################################################################
  #  Artifact download
  ####################################################################          
  download-artifact:
    runs-on: [self-hosted]
    environment: ${{ inputs.environment }}

    steps:
      # Clean the workspace to help clean up self-Hosted runners prior to deployment
      - uses: AutoModality/action-clean@v1
             
      # Download the artifact from GitHub artifacts
      - name: Download artifact into a new directory named artifact
        run: |
          mkdir ./artifact
          ARTIFACT_ID=$(echo ${{ inputs.artifact-id }}|grep -P '[0-9]+' -o | tail -1)
          curl -L -o artifact.zip \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GH_PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/liquibase/CS_Postgres/actions/artifacts/$ARTIFACT_ID/zip
      
      # Unzip the artifact into the newly created ./artifact directory
      - name: Unzip artifact
        run: |
          unzip artifact.zip -d ./artifact
          du -ah
          
  ####################################################################
  #  Deploy the artifact to the requested environment
  ####################################################################
  database-deploy:
    needs: [download-artifact]
    runs-on: [self-hosted]
    environment: ${{ inputs.environment }}

    # Execute the DB update from the downloaded and unzipped artifact
    # Note that this artifact is being loaded from ./artifact. Loading different changelogs can
    # cause problems when creating the unique identifier of changesets. In our changelog,
    # we've specified a logicalFilePath which is used as a key to the correct file, regardless of
    # where it resides on the file system
    steps:
        # Execute the Flow file
      - name: Run flow
        run: |
          liquibase flow \
             --flow-file=${{ env.LB_FLOW_FILE }}               

####################################################################
#  Artifact creation for Reports
####################################################################
  create-reports-artifact:
    needs: [database-deploy]
    runs-on: [self-hosted]
    environment: ${{ inputs.environment }}

    steps:
      # Save reports as artifact
      - uses: actions/upload-artifact@v3
        with:
          name: REPORTS-${{ github.run_id }}.${{ github.run_number }}.zip
          path: reports/